### ISSUE TITLE
File request and your SMTP could be down

### ISSUE THREAD

**Issue by docgalaxyblock** [leonvandenbeukel/Round-LED-Clock#2]
Hi Leon,

I tried to send a mail to your youtube mail, the mail got a delivery error at your smtp server.
So here is my mail:

Would it be possible that you can please send mir your Fusion Project or the files as steps?
I want to print the hole ring in one part beacause m Printer is so big ^^

Greeting from Germany ^^

**Comment by leonvandenbeukel** [comment]
Hi, 

I've added a complete ring for you to print in the STL files. Also added a segment with thicker walls as someone else requested.

Greetings from the Netherlands :-)
Leon
