### ISSUE TITLE
Frequent Change to false time

### ISSUE THREAD

**Issue by arne4** [leonvandenbeukel/Round-LED-Clock#5]
The LEDs show a wrong time every few minutes or seconds. This false indication lasts less than a second.
- I replaced the wemos, but nothing has changed.
- Solder connection also new and no change

Is this behaviour known or what else could it be?
Normally I would guess a problem with the wemos, but that should be excluded.

Thank you, Arne

**Comment by ThEWiZ76** [comment]
Same problem here https://www.youtube.com/watch?v=w4xsj8hr7YY

**Comment by ThEWiZ76** [comment]
I've merged the nighttime/hour gold/colormixing pull requests in the version I am running, then the problem is more visible. It looks like the whole register shifts forward. I think it's a FastLED lib issue rather than the code of this project. I currently use 3.1.6 and you?

**Comment by ThEWiZ76** [comment]
I've done a little bit of reading, some people say the issue can occur when the power supply to the led strip isn't sufficient. I have upgraded my library to 3.2.6 and my issue is resolved.

**Comment by arne4** [comment]
I upgraded to 3.2.6 and changed the power supply (also with direct supply of the LEDs) but unfortunately no change in behaviour....

:(
Such a beautiful clock, but currently it is not working!

**Comment by arne4** [comment]
I just realised, that my IDE tricked me... I thought I updated to 3.2.6, but actually I still stick to the old FASTled library.
NOW, I updated and also everything is fine!
Thanks for this wonderful clock!
Arne
