### ISSUE TITLE
Newbie error in  compiling/flashing

### ISSUE THREAD

**Issue by RafaelCota** [leonvandenbeukel/Round-LED-Clock#8]
Hi,
I'm trying to flash the program to the controller, but I'm getting some errors (files attached)

I was wondering if you could put me in the right track. I really want to get this project done. It's a good one.

Thank you in advanced,

[Errors-NonVerbose.pdf](https://github.com/leonvandenbeukel/Round-LED-Clock/files/3294463/Errors-NonVerbose.pdf)
[Errors-Verbose.pdf](https://github.com/leonvandenbeukel/Round-LED-Clock/files/3294464/Errors-Verbose.pdf)

**Comment by leonvandenbeukel** [comment]
Hi,

If you use a generic esp board you probably cannot use pin D6, try using
only the pin number.

Regards,
Leon

Op zo 16 jun. 2019 20:45 schreef RafaelCota <notifications@github.com>:
