### ISSUE TITLE
compilation error

### ISSUE THREAD

**Issue by Pierre01480** [leonvandenbeukel/Round-LED-Clock#9]
Hello Leon,
I am admiring of all yours creations . Great !
I would like to make the WIFI clock (with the Wemos d1 mini board)
I selected the board LOLIN (Wemos) D1 R2 & mini (in the choise list of boards there is no Wemos D1 mini)
Below is the error message when compiling
Since 3 weeks I try to solve the problem .... Without success
If I use the library Adafruit_Neopixel (of course by modifying your program a bit): it works .... But I would like to understand my mistake
Thanks for your help

[errors.pdf](https://github.com/leonvandenbeukel/Round-LED-Clock/files/3310986/errors.pdf)

**Comment by ThEWiZ76** [comment]
You should upgrade your fastled library to at least 3.2.6

**Comment by Pierre01480** [comment]
thanks a lot for your help

 

De : ThEWiZ76 [mailto:notifications@github.com] 
Envoyé : vendredi 21 juin 2019 08:01
À : leonvandenbeukel/Round-LED-Clock <Round-LED-Clock@noreply.github.com>
Cc : Pierre01480 <pjp.pascal@wanadoo.fr>; Author <author@noreply.github.com>
Objet : Re: [leonvandenbeukel/Round-LED-Clock] compilation error (#9)

 

You should upgrade your fastled library to at least 3.2.6
